# pod-template.yaml (Final Version)

apiVersion: v1
kind: Pod
spec:
  # The service account in your EKS 'jenkins' namespace
  serviceAccountName: jenkins-agent
  
  containers:
  # Python container for verification steps
  - name: python
    image: python:3.11-slim
    command: ["sleep"]
    args: ["infinity"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"

  # Podman container for building images
  - name: podman
    image: quay.io/podman/stable
    command: ["sleep"]
    args: ["infinity"]
    securityContext:
      privileged: true

  # AWS CLI container for ECR login
  - name: aws-cli
    image: amazon/aws-cli:latest
    command: ["sleep"]
    args: ["infinity"]
