# pod-template.yaml (리소스 추가 버전)

apiVersion: v1
kind: Pod
spec:
  nodeSelector:
   # capacity-type: on-demand
    workload: core

  serviceAccountName: jenkins-agent
  containers:
  - name: python
    image: python:3.9-slim
    command: ["sleep"]
    args: ["infinity"]
    # 이 부분을 추가하여 Pod의 리소스를 늘립니다.
    resources:
      requests:
        memory: "1Gi" # 최소 1Gi 메모리 요청
        cpu: "500m"   # 최소 0.5 CPU 코어 요청
      limits:
        memory: "2Gi" # 최대 2Gi 메모리 사용 제한
        cpu: "1"      # 최대 1 CPU 코어 사용 제한

  - name: podman
    image: quay.io/podman/stable
    command: ["sleep"]
    args: ["infinity"]
    securityContext:
      privileged: true

  - name: aws-cli
    image: amazon/aws-cli:latest
    command: ["sleep"]
    args: ["infinity"]
