pipeline {
    agent {
        kubernetes {
            cloud 'kubernetes'    // Cloud 이름
            namespace 'jenkins'
            defaultContainer 'jnlp'
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: crawler-agent
spec:
  containers:
  - name: python
    image: python:3.11-slim
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  - name: podman
    image: quay.io/podman/stable
    command:
    - cat
    tty: true
  - name: aws-cli
    image: amazon/aws-cli:latest
    command:
    - cat
    tty: true
  - name: jnlp
    image: jenkins/inbound-agent:latest
    env:
    - name: JENKINS_URL
      value: "http://hihypipe-jenkins-alb-610592627.ap-northeast-2.elb.amazonaws.com:8080"
    - name: JENKINS_WEB_SOCKET
      value: "true"
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  restartPolicy: Never
"""
        }
    }
    stages {
        stage('Test') {
            steps {
                container('python') {
                    sh 'python --version'
                }
            }
        }
    }
}

