apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    capacity-type: on-demand
    workload: core
  serviceAccountName: jenkins-agent
  containers:
  - name: python
    image: python:3.9-bullseye
    command: ["sleep"]
    args: ["infinity"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"
  - name: podman
    image: quay.io/podman/stable
    command: ["sleep"]
    args: ["infinity"]
    securityContext:
      privileged: true
  - name: aws-cli
    image: amazon/aws-cli/latest
    command: ["sleep"]
    args: ["infinity"]
